package view;

import java.io.IOException;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.input.MouseEvent;
import javafx.scene.layout.AnchorPane;
import javafx.scene.layout.BorderPane;

public class HomeController {

	@FXML
	private BorderPane borderPane;


	// Event Listener on Button.onMouseClicked
	@FXML
	public void clear(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button.onMouseClicked
	@FXML
	public void chama1(MouseEvent event) {
		loadChama("lista_tipoOleo");
	}
	// Event Listener on Button.onMouseClicked
	@FXML
	public void chama2(MouseEvent event) {
		loadChama("lista_tipoPneu");
	}
	// Event Listener on Button.onMouseClicked
	@FXML
	public void chama3(MouseEvent event) {
		loadChama("lista_tipoFreio");
	}
	 @FXML
		public void chama4(MouseEvent event) {
			loadChama("lista_marcaOleo");
		}
	 @FXML
		public void chama5(MouseEvent event) {
			loadChama("lista_marcaPneu");
		}
	 @FXML
		public void chama6(MouseEvent event) {
			loadChama("lista_marcaFreio");
		}
	 @FXML
		public void chama7(MouseEvent event) {
			loadChama("lista_usuarios");
		}
	 @FXML
		public void chama8(MouseEvent event) {
			loadChama("controle_manutencao");
		}

	 @FXML
		public void chama9(MouseEvent event) {
			loadChama("lista_classes");
		}

	 @FXML
		public void chama10(MouseEvent event) {
			loadChama("lista_onibus");
		}


	public  void loadChama(String chama){

		AnchorPane abrirTela = null;

		try {
			abrirTela = (AnchorPane)FXMLLoader.load(HomeController.class.getResource(chama+".fxml"));


		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}

		borderPane.setCenter(abrirTela);




	}

}
